version: '3.9'
services:
  ssh.cyrhades.fr:
    build: ./.docker/ssh
  webssh.cyrhades.fr:
    build: ./.docker/webssh
    ports:
      - ${PORT}:8888
  fifty-shades-of-white.cyrhades.fr:
    image: anssi/fcsc2024-reverse-fifty-shades-of-white:latest
    ports:
      - ${PORT_SSH}:4000
